### PR TITLE
Sort value validation

### LINKED ISSUE #89: Validator: implement `sort` check
Currently `sort` setting is validated only by type. That's why anything can be written there: [incorrect time unit](https://apps.axibase.com/chartlab/9a0dd4c6/14/) or [incorrect value](https://apps.axibase.com/chartlab/9a0dd4c6/85/)
Add validation for `sort` setting

### PR DESCRIPTION
**Pull request by PolinaShneider**
Closes #89 

Added sort value validation. Generally it supports the [following](https://github.com/axibase/charts-language-service/issues/89#issuecomment-538432677) syntax.

Also added calendar-specific validation rules, allowing using [statistic function](https://axibase.com/docs/charts/widgets/calendar-chart/#sort-by-statistic), specified as number of [time units](https://axibase.com/docs/atsd/api/data/series/time-unit.html). Calendar widget supports **both** syntaxes.

## What is validated now:
- Correctness of general sort setting syntax (via regex)
- Statistic function value is widget type specific
- Statistic function contains only known functions, time units, and time units numerical value is in right format.

Error messages with test-cases are demonstrated below. Texts shown to user can be discussed. Let me know, if we need additional details in error messages ⤵️

1. Widget chart, wrong setting syntax (commas missing):
image

2. Widget calendar — mistake is same as above, though widget type specific syntax suggestion is shown:
image

3. Widget calendar — wrong time-units:
image

### CODE REVIEW

File: src/regExpressions.ts [hunk 1]
```diff
@@ -135,12 +134,21 @@ export const VAR_OPEN_BRACKET: RegExp = /(=)?\s*[\[\{\(](|.*,)\s*$/;
...
 export const KEYWORDS_REGEX: RegExp = new RegExp(`^[ \t]*(?:${CONTROL_KEYWORDS.join("|")})[ \t]*`, "g");
 
 // position = 1-1, 2-2
 export const POSITION_REGEX: RegExp = /(\d+-\d+)(?:\s*,\s*)(\d+-\d+)/;
 
+// stat_name('count unit'), for example: sum(5 minute), avg(10 second)
+export const STAT_COUNT_UNIT = new RegExp(
+    `([a-z_]+)\\s*\\((.*)\\)\\s*((?:asc|desc)(?:ending)?)?$`,
+    "i"
+);
```
Comment (annstriganova) [inline src/regExpressions.ts]: Is it necessary to use `new RegExp` instead of `/([a-z_]+)\s*\((.*)\)\s*((?:asc|desc)(?:ending)?)?$/i`?

File: src/relatedSettingsRules/valueValidation/sort.ts [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+                }
+
+                if (errors.length) {
+                    errorMessage = errors.join(". ");
+                }
+                break;
+            }
+            default: {
+                if (incorrectSyntax(sort.value)) {
+                    errorMessage = `Incorrect syntax. '${sort.value}' doesn't match 'value asc|desc' schema`;
```
Comment (annstriganova) [inline src/relatedSettingsRules/valueValidation/sort.ts]: I suggest to move it to function `defaultMessage(sortValue: string)`.

File: src/regExpressions.ts (hunk 1 above)
Comment (annstriganova) [reply src/regExpressions.ts]: Also it doesn't catch this: `sum("5 minute')`

File: src/relatedSettingsRules/valueValidation/sort.ts [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+                    const [, unit] = contents.split(" ");
+                    if (STAT_FUNCTIONS.indexOf(stat) < 0) {
+                        errors.push(`Unknown stat function: ${stat}`);
+                    }
+
+                    if (unit && INTERVAL_UNITS.indexOf(unit) < 0) {
+                        errors.push(`Unknown interval unit: ${unit}`);
+                    }
+                } else {
+                    if (incorrectSyntax(sort.value)) {
```
Comment (annstriganova) [inline src/relatedSettingsRules/valueValidation/sort.ts]: Calendar supports only one sorting rule.

File: src/relatedSettingsRules/valueValidation/sort.ts [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+        }
+    }
+};
+
+/**
+ * Check each value item of 'sort' setting for syntax correctness
+ * @param value - 'sort' setting value
+ */
+function incorrectSyntax(value: string): boolean {
+    return value.split(",").some(element => !SORT_REGEX.test(element.trim()));
```
Comment (annstriganova) [inline src/relatedSettingsRules/valueValidation/sort.ts]: It would be useful to highlight only broken items, instead of the whole value.

File: src/test/sort.test.ts [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+        const validator = new Validator(config);
+        const actual: Diagnostic[] = validator.lineByLine();
+        const expected: Diagnostic[] = [];
+        assert.deepStrictEqual(actual, expected, `Config: \n${config}`);
+    });
+});
+
+suite("Incorrect sort value", () => {
+    test("Wrong sort order", () => {
+        const config = baseConfig("sort = value ASCE");
```
Comment (annstriganova) [inline src/test/sort.test.ts]: If it's not very difficult, could we throw more specific warning? I mean `Incorrect sort order, use ASC or DESC` and highlight exactly `ASCE` word.

File: src/test/sort.test.ts [hunk 6]
```diff
@@ -0,0 +1,158 @@
...
+            createDiagnostic(
+                createRange(4, 4, 8),
+                "Incorrect syntax. 'value asce' doesn't match 'value asc|desc' schema"
+            )
+        ];
+        assert.deepStrictEqual(actual, expected, `Config: \n${config}`);
+    });
+
+    test("Wrong sort value, no separating commas", () => {
+        const config = baseConfig("sort = not valid");
```
Comment (annstriganova) [inline src/test/sort.test.ts]: Is it possible to suggest more specific fix? I mean the following: `Incorrect syntax. Replace with "not, valid" or "not ASC|DESC"`.

File: src/test/sort.test.ts [hunk 7]
```diff
@@ -0,0 +1,158 @@
...
+    });
+
+    test("Incorrect statistic function for calendar", () => {
+        const config = baseConfig("sort = test(5 minute) ", "calendar");
+        const validator = new Validator(config);
+        const actual: Diagnostic[] = validator.lineByLine();
+        const expected: Diagnostic[] = [
+            createDiagnostic(
+                createRange(4, 4, 8),
+                "Unknown stat function: test"
```
Comment (annstriganova) [inline src/test/sort.test.ts]: Please, add a list of possible stat functions, refer to [`supportedUnits`](https://github.com/axibase/charts-language-service/blob/7e069d92b82452b6c4ad86e2303033b0c5e72533/src/messageUtil.ts#L62).

File: src/test/sort.test.ts [hunk 8]
```diff
@@ -0,0 +1,158 @@
...
+    });
+
+    test("Incorrect time units in statistic function", () => {
+        const config = baseConfig("sort = max(5 hello) ", "calendar");
+        const validator = new Validator(config);
+        const actual: Diagnostic[] = validator.lineByLine();
+        const expected: Diagnostic[] = [
+            createDiagnostic(
+                createRange(4, 4, 8),
+                "Unknown interval unit: hello"
```
Comment (annstriganova) [inline src/test/sort.test.ts]: Please, add [`supportedUnits`](https://github.com/axibase/charts-language-service/blob/7e069d92b82452b6c4ad86e2303033b0c5e72533/src/messageUtil.ts#L62).

File: src/relatedSettingsRules/valueValidation/sort.ts (hunk 3 above)
Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: What do you mean? Is sorting value `metric, value ASC` irrelevant for calendar?

File: src/regExpressions.ts (hunk 1 above)
Comment (PolinaShneider) [reply src/regExpressions.ts]: Do me have to catch case with unmatched quotes?

File: src/relatedSettingsRules/valueValidation/sort.ts (hunk 3 above)
Comment (annstriganova) [reply src/relatedSettingsRules/valueValidation/sort.ts]: Yes, irrelevant. Moreover, it supports only the following:
a) `name [ASC|DESC]`  - sorts by label;
b) `stat_name(['"]count unit["'])` - sorts by stat.

* `sort = name ASC, sum("5 minute") DESC` is incorrect, because `sum("5 minute") DESC` is ignored.
* `sort = metric, value ASC` is ignored, because `metric` and `value` are not supported.

File: src/regExpressions.ts (hunk 1 above)
Comment (annstriganova) [reply src/regExpressions.ts]: It doesn't seem to be very difficult. Regex used by Charts:

```js
/**
 * sum(5 minute), sum("5 minute") or sum('5 minute')
 */
var STAT_CALL = /(\w+)\((['"])?(\d+\s+\w+)\2\)/i;
```

File: src/test/sort.test.ts (hunk 5 above)
Comment (PolinaShneider) [reply src/test/sort.test.ts]: But how can we distinguish between `value1 value2` (comma is missing) and `value1 MISSPELLED_ORDER`?

Comment (annstriganova) [reply src/test/sort.test.ts]: Yes, to difficult. If possible, try just [this](https://github.com/axibase/charts-language-service/pull/92#discussion_r343076196).

File: src/relatedSettingsRules/valueValidation/sort.ts (hunk 4 above)
Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: I think, we will have trouble with highlighting specific range, containing a mistake. We have no access to current config line, only to Setting TextRange and to value string.

Okay, we can get current indent from Setting TextRange. But what about value's real position? I mean, we don't know, how many spaces we have between `=` sign unless the doc is formatted.

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: It can result in something like this. I wanted to highlight `hourr`

image

Comment (annstriganova) [reply src/relatedSettingsRules/valueValidation/sort.ts]: We could store the whole line, where setting is declared, as `Setting`'s field and calculate range using `indexOf`, but you are right, it's better to open separate PR with any such refactoring. In addition, it's not an important feature, so let's postpone it.

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: And what about current PR? Should I show all warnings at Setting's TextRange?

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: Alternatively, if a user made two mistakes (incorrect time units and unknown stat function, for instance), show only the first warning. At the moment we cannot show two warnings at the same range without concatenating error messages into one.

Or, probably, you have a better idea

Comment (annstriganova) [reply src/relatedSettingsRules/valueValidation/sort.ts]: > And what about current PR? Should I show all warnings at Setting's TextRange?

Yes.

> At the moment we cannot show two warnings at the same range without concatenating error messages into one.

If I understand correctly, at the moment error messages are concatenated, I think it's convenient.

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: All right, reverted changes back. I think, PR is ready for re-review :)

File: src/relatedSettingsRules/valueValidation/sort.ts [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+                        errors.push(`Unknown stat function: ${stat} \n${supportedStatFunctions()}`);
+                    }
+
+                    if (unit && INTERVAL_UNITS.indexOf(unit) < 0) {
+                        errors.push(`Unknown interval unit: ${unit} \n${supportedUnits()}`);
+                    }
+                } else if (!SORT_REGEX.test(sort.value)) {
+                    /**
+                     * Calendar supports only single sort value: 'val1 ASC, val2 DES' not allowed
+                     */
```
Comment (annstriganova) [inline src/relatedSettingsRules/valueValidation/sort.ts]: Since there is only `name` is [supported](https://github.com/axibase/charts-language-service/pull/92#discussion_r343097489) in Calendar, this check is need to be improved.

File: src/regExpressions.ts [hunk 10]
```diff
@@ -135,12 +134,18 @@ export const VAR_OPEN_BRACKET: RegExp = /(=)?\s*[\[\{\(](|.*,)\s*$/;
...
+export const SORT_REGEX: RegExp = /^(\w+)(?:\s+)?((?:asc|desc)(?:ending)?)?$/;
+
 // sql|script|if|for|var|list|csv|expr
 export const KEYWORDS_REGEX: RegExp = new RegExp(`^[ \t]*(?:${CONTROL_KEYWORDS.join("|")})[ \t]*`, "g");
 
 // position = 1-1, 2-2
 export const POSITION_REGEX: RegExp = /(\d+-\d+)(?:\s*,\s*)(\d+-\d+)/;
 
+// stat_name('count unit'), for example: sum(5 minute), avg(10 second)
+export const STAT_COUNT_UNIT = /([a-z_]+)\((['"])?(.+)\2\)\s*((?:asc|desc)(?:ending)?)?$/i;
```
Comment (annstriganova) [inline src/regExpressions.ts]: This will be better `(.*)\((['"])?(.+)\2\)\s*((?:asc|desc)(?:ending)?)?$`, to catch `s$m(5 minute)`.

File: src/relatedSettingsRules/valueValidation/sort.ts [hunk 11]
```diff
@@ -0,0 +1,88 @@
...
+                 * Check that correct, yet unsuitable for current widget type syntax isn't used
+                 * TODO: in case we have more syntaxes, put type-specific regexes into array
+                 */
+                if (STAT_COUNT_UNIT.exec(sort.value) !== null) {
+                    errors.push(`Incorrect syntax for widget type '${widgetType}'. ` +
+                    `'${sort.value}' doesn't match 'value ASC|DESC' schema`);
+                } else if (incorrectMultiValueSyntax(sort.value)) {
+                    if (sort.value.indexOf(",") < 0) {
+                        const [first, second] = sort.value.split(" ");
+                        errors.push(`Incorrect syntax. Replace with '${first}, ${second}' or '${first} ASC|DESC'`);
```
Comment (annstriganova) [inline src/relatedSettingsRules/valueValidation/sort.ts]: Minor improvement: since order is optional, this would be better `'${first}[ ASC|DESC]'`.

File: src/relatedSettingsRules/valueValidation/sort.ts (hunk 9 above)
Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: If I am not mistaken, order is also supported. So, according to [docs](https://axibase.com/docs/charts/widgets/calendar-chart/#sort), `name ASC` will be a valid value. What's wrong with the regex then?

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: At the moment algorithm is the following:

1) We check specific stat syntax and validate it for correctness
2) If stat syntax regex match is null, we check via SORT_REGEX. It's strict enough: doesn't allow commas, extra spaces, words other than name (before space) and optional ASC|DESC order. If this regex failed, we raise a warning

Comment (annstriganova) [reply src/relatedSettingsRules/valueValidation/sort.ts]: Selection_004

The only field that Calendar supports sort by is label, and keyword `name` corresponds to sorting by label.

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: Corrected that

File: src/regExpressions.ts [hunk 12]
```diff
@@ -144,7 +144,7 @@ export const KEYWORDS_REGEX: RegExp = new RegExp(`^[ \t]*(?:${CONTROL_KEYWORDS.j
 export const POSITION_REGEX: RegExp = /(\d+-\d+)(?:\s*,\s*)(\d+-\d+)/;
 
 // stat_name('count unit'), for example: sum(5 minute), avg(10 second)
-export const STAT_COUNT_UNIT = /([a-z_]+)\((['"])?(.+)\2\)\s*((?:asc|desc)(?:ending)?)?$/i;
+export const STAT_COUNT_UNIT = /(.*)\((['"])?(.+)\2\)\s*((?:asc|desc)(?:ending)?)?$/;
```
Comment (VeselovAlex) [inline src/regExpressions.ts]: Does it mean that `('1 second')` and `go?!* 23('2 minute')` are supported?

File: src/relatedSettingsRules/valueValidation/sort.ts [hunk 13]
```diff
@@ -37,11 +37,11 @@ const rule: Rule = {
...
                         errors.push(`Unknown interval unit: ${unit} \n${supportedUnits()}`);
                     }
-                } else if (!SORT_REGEX.test(sort.value)) {
+                } else if (!NAME_REGEX.test(sort.value)) {
                     /**
-                     * Calendar supports only single sort value: 'val1 ASC, val2 DES' not allowed
+                     * Calendar supports only single sort by name syntax. 'val1 ASC, val2 DES' is not allowed
                      */
-                    errors.push(`Incorrect syntax. '${sort.value}' doesn't match 'value ASC|DESC' schema`);
+                    errors.push(`Incorrect syntax. '${sort.value}' doesn't match 'value' schema`);
```
Comment (VeselovAlex) [inline src/relatedSettingsRules/valueValidation/sort.ts]: Is `name desc` value supported?  See https://axibase.com/docs/charts/widgets/calendar-chart/#sort.
Also why not provide calendar specific message if Syntax is coorect, but multiple values are present?

Comment (VeselovAlex) [reply src/relatedSettingsRules/valueValidation/sort.ts]: Also isn't sort.value already trimmed? In this case you can simplify regular expression

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: According to docs, it is a valid syntax. Probably, I'm missing something. 
image

Comment (PolinaShneider) [reply src/relatedSettingsRules/valueValidation/sort.ts]: @VeselovAlex what do you mean? 
> Also why not provide calendar specific message if Syntax is coorect, but multiple values are present?

Multiple stat functions?

Comment (VeselovAlex) [reply src/relatedSettingsRules/valueValidation/sort.ts]: > @VeselovAlex what do you mean?
> 
> > Also why not provide calendar specific message if Syntax is coorect, but multiple values are present?
> 
> Multiple stat functions?

If on types `sort = value ASC, name DESC` which is not supported only in calendar, it would be better to not reject this value with invalid syntax error, but with something like `Multiple sorting columns are not supported in calendar`

File: src/regExpressions.ts (hunk 12 above)
Comment (PolinaShneider) [reply src/regExpressions.ts]: Yes, the second variant is also captured. It was Anya's suggestion. Do you think that the regex should be more strict, like allowing only alphanumeric characters in first capturing group?

File: src/constants.ts [hunk 14]
```diff
@@ -25,3 +25,5 @@ export const RELATIONS: string[] = [
 export const BOOLEAN_KEYWORDS: string[] = [
     "false", "no", "null", "none", "0", "off", "true", "yes", "on", "1",
 ];
+
+export const STAT_FUNCTIONS: string[] = ["sum", "min", "max", "avg", "first", "last"];
```
Comment (annstriganova) [inline src/constants.ts]: Please, add comment: `Stat functions, supported by Calendar sort`
